#!/usr/bin/env python3
"""Regenerate ``gh_flags.yaml`` from the ``gh`` CLI installed on this machine.

The fixture it writes is what ``tests/test_skill_docs.py`` checks the documented
``gh`` fallback commands against. It is a *fixture*, not a live probe: the tests
must pass on a host with no ``gh`` at all (CI), so the flag lists are committed
and this script is run by hand when a documented command grows a new flag.

Usage::

    .venv/bin/python tests/fixtures/gen_gh_flags.py          # rewrite the fixture
    .venv/bin/python tests/fixtures/gen_gh_flags.py --print  # dump to stdout

Only the commands the skill docs actually invoke are collected — ``COMMANDS``
below is that list, and adding a command to the docs means adding it here.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

# Every ``gh`` command the shared skill docs and references invoke. A key is the
# literal prefix as written on the command line; `gh api` takes no subcommand.
COMMANDS = (
    "gh api",
    "gh auth refresh",
    "gh auth status",
    "gh issue comment",
    "gh issue create",
    "gh issue edit",
    "gh issue view",
    "gh pr checks",
    "gh pr create",
    "gh pr list",
    "gh project field-list",
    "gh project item-add",
    "gh project item-edit",
    "gh project item-list",
)

# `  -F, --body-file file` / `      --type name` — both shapes, long flag only.
_FLAG_RE = re.compile(r"^\s+(?:-(?P<short>[A-Za-z]), )?--(?P<long>[a-z][a-z0-9-]*)")
_SHORT_RE = re.compile(r"^\s+-(?P<short>[A-Za-z]), --")


def flags_for(command: str) -> tuple[list[str], list[str]]:
    """Return (long_flags, short_flags) parsed from ``<command> --help``."""
    proc = subprocess.run(
        [*command.split(), "--help"], capture_output=True, text=True, check=False
    )
    text = proc.stdout or proc.stderr
    longs: set[str] = set()
    shorts: set[str] = set()
    in_flags = False
    for line in text.splitlines():
        if re.match(r"^[A-Z][A-Z ]+$", line.strip()):
            in_flags = line.strip() in {"FLAGS", "INHERITED FLAGS"}
            continue
        if not in_flags:
            continue
        match = _FLAG_RE.match(line)
        if match:
            longs.add("--" + match.group("long"))
        short = _SHORT_RE.match(line)
        if short:
            shorts.add("-" + short.group("short"))
    return sorted(longs), sorted(shorts)


def gh_version() -> str:
    proc = subprocess.run(["gh", "--version"], capture_output=True, text=True, check=False)
    first = (proc.stdout or "").splitlines()
    return first[0].strip() if first else "unknown"


def render() -> str:
    lines = [
        "# Generated by tests/fixtures/gen_gh_flags.py — do not hand-edit.",
        "#",
        "# Flags accepted by each `gh` command the shared skill docs invoke. The docs",
        "# are checked against this list offline, so a host with no `gh` (CI) still",
        "# catches a documented flag that does not exist. Regenerate after upgrading",
        "# `gh` or documenting a new command.",
        "_generated_by: tests/fixtures/gen_gh_flags.py",
        f"_gh_version: {gh_version()!r}",
        "commands:",
    ]
    for command in COMMANDS:
        longs, shorts = flags_for(command)
        if not longs:
            print(f"warning: no flags parsed for {command!r}", file=sys.stderr)
        lines.append(f"  {command!r}:")
        lines.append("    long: [" + ", ".join(repr(f) for f in longs) + "]")
        lines.append("    short: [" + ", ".join(repr(f) for f in shorts) + "]")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--print", action="store_true", dest="to_stdout")
    args = parser.parse_args()
    text = render()
    if args.to_stdout:
        sys.stdout.write(text)
        return 0
    target = Path(__file__).with_name("gh_flags.yaml")
    target.write_text(text, encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
